require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'B2B_NEW_THEME' do
  config = use_native_modules!
    pod 'Firebase', :modular_headers => true
    pod 'FirebaseCore', :modular_headers => true
    pod 'FirebaseCoreInternal', :modular_headers => true
    pod 'GoogleUtilities', :modular_headers => true
    pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
    pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
    pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    :flipper_configuration => false,
  )
  $RNFirebaseAsStaticFramework = true

  pod 'react-native-location', :path => '../node_modules/react-native-location'

  target 'B2B_NEW_THEMETests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  # use_frameworks! :linkage => :static

  post_install do |installer|
    react_native_post_install(installer)
  end
end