POST http://automatestaging-724985329.ap-south-1.elb.amazonaws.com:8083/dashboard/v2/get_target_params
Content-Type: application/json

{"endDate":"2022-10-31","loggedInEmpId":947,"startDate":"2022-10-01","levelSelected":null,"empId":947,"pageNo":0,"size":5}

###
POST http://automatestaging-724985329.ap-south-1.elb.amazonaws.com:8092/dashboard/v2/get_target_params_model_source
Content-Type: application/json

{
  "orgId": 18,
  "endDate": "2022-09-30",
  "loggedInEmpId": 919,
  "empId": 919,
  "startDate": "2022-09-01",
  "levelSelected": null,
  "pageNo": 0,
  "size": 100
}

###
POST http://automatestaging-724985329.ap-south-1.elb.amazonaws.com:8092/dashboard/v2/get_target_params_model_source
Content-Type: application/json

{
  "endDate": "2022-09-30",
  "loggedInEmpId": 947,
  "empId": 947,
  "startDate": "2022-09-01",
  "levelSelected": null
}

###
